CREATE TABLE MOCKDATABASEFORITRAK 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 NOT NULL 
, FIRSTNAME VARCHAR2(50 BYTE) NOT NULL 
, MIDDLENAME VARCHAR2(50 BYTE) 
, LASTNAME VARCHAR2(50 BYTE) NOT NULL 
, SUFFIX VARCHAR2(20 BYTE) 
, BIRTHDATE DATE 
, GENDER VARCHAR2(50 BYTE) NOT NULL 
, SEX CHAR(1 BYTE) NOT NULL 
, HOUSENUMBER VARCHAR2(20 BYTE) 
, STREET VARCHAR2(20 BYTE) NOT NULL 
, CIVILSTATUS VARCHAR2(50 BYTE) NOT NULL 
, RELIGION VARCHAR2(50 BYTE) NOT NULL 
, STATUS CHAR(7 BYTE) NOT NULL 
, NATIONALITY VARCHAR2(50 BYTE) NOT NULL 
, OCCUPATION VARCHAR2(50 BYTE) NOT NULL 
, SSS NUMBER 
, PHILHEALTH NUMBER 
, TIN NUMBER 
, TELEPHONENUMBER NUMBER NOT NULL 
, MOBILENUMBER NUMBER 
, HEIGHT FLOAT(126) NOT NULL 
, WEIGHT FLOAT(126) NOT NULL 
, EMAILADDRESS VARCHAR2(50 BYTE) 
, IMAGE1 BLOB 
, IMAGE2 BLOB 
, CONSTRAINT MOCKDB_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MOCKDB_PK ON MOCKDATABASEFORITRAK (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL 
LOB (IMAGE1) STORE AS SYS_LOB0000074012C00024$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
) 	
LOB (IMAGE2) STORE AS SYS_LOB0000074012C00025$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);
