/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itrak;

/**
 *
 * @author user
 */

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;



public class InsertForm_Resident extends javax.swing.JFrame {

    /**
     * Creates new form JFrameForm
     */
    
     
    static final String USER = "system"; //Database Username
    static final String PASS = "Admin123"; //Your Account Password
    static final String DATABASE = "ztt"; //Database Name
    static final String SERVER_IP = "localhost"; //Your Database Server IP (run ipconfig in cmd)
    static final String PORT = "1521";
    static final String DB_URL = "jdbc:oracle:thin:@" + SERVER_IP + ":" + PORT + ":" +DATABASE;   
    public InsertForm_Resident() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backButton = new javax.swing.JLabel();
        Photo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uploadPicture = new javax.swing.JButton();
        fileName1x1 = new javax.swing.JTextField();
        img1x1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fileNameSignature = new javax.swing.JTextField();
        uploadSignature = new javax.swing.JButton();
        imageSignature = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Form = new javax.swing.JPanel();
        firstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        middleName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        suffix = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        date = new javax.swing.JFormattedTextField();
        sexBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        civilStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        religion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nationality = new javax.swing.JTextField();
        lotNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        occupation = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        sss = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        philHealth = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tin = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        SideBar = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        homePage = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        databasePage = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        documentPage = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        documentLabel = new javax.swing.JLabel();
        reportsPage = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        reportLabel = new javax.swing.JLabel();
        officialsPage = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        officialLabel = new javax.swing.JLabel();
        aboutUs = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        aboutUsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 178, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 50));

        Photo.setBackground(new java.awt.Color(255, 255, 255));
        Photo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile Picture");
        Photo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 166, -1));

        uploadPicture.setText("UPLOAD");
        uploadPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPictureActionPerformed(evt);
            }
        });
        Photo.add(uploadPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 166, -1));

        fileName1x1.setEditable(false);
        fileName1x1.setBorder(null);
        fileName1x1.setOpaque(false);
        fileName1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileName1x1ActionPerformed(evt);
            }
        });
        Photo.add(fileName1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 166, -1));

        img1x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1x1.setText("PIRMA HERE");
        img1x1.setToolTipText("");
        img1x1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Photo.add(img1x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 166, 166));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Signature");
        Photo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 166, -1));

        fileNameSignature.setEditable(false);
        fileNameSignature.setToolTipText("");
        fileNameSignature.setBorder(null);
        fileNameSignature.setOpaque(false);
        Photo.add(fileNameSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 166, -1));

        uploadSignature.setText("UPLOAD");
        uploadSignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadSignatureActionPerformed(evt);
            }
        });
        Photo.add(uploadSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 166, -1));

        imageSignature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageSignature.setText("PIRMA HERE");
        imageSignature.setToolTipText("");
        imageSignature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Photo.add(imageSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 166, 166));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        Photo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 166, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        Photo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 166, 10));

        jPanel3.add(Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 210, 590));

        Form.setBackground(new java.awt.Color(255, 255, 255));
        Form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        Form.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Contact Information");
        Form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));
        Form.add(middleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        jLabel5.setText("Middle Name");
        Form.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, -1));
        Form.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 150, -1));

        jLabel2.setText("Last name*");
        Form.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, -1));

        suffix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suffixActionPerformed(evt);
            }
        });
        Form.add(suffix, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 48, -1));

        jLabel6.setText("Suffix");
        Form.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 50, -1));

        date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        Form.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));

        sexBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        Form.add(sexBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel8.setText("Sex*");
        Form.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 34, -1));

        jLabel9.setText("Gender*");
        Form.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 100, 10));

        gender.setName(""); // NOI18N
        Form.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 100, -1));

        jLabel7.setText("Birth Date");
        Form.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        civilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widowed", "Divorced" }));
        civilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilStatusActionPerformed(evt);
            }
        });
        Form.add(civilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, -1));

        jLabel3.setText("Civil Status*");
        Form.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));
        Form.add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, -1));

        jLabel18.setText("Telephone Number");
        Form.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, -1));
        Form.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, -1));

        jLabel19.setText("Mobile Number");
        Form.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, -1));
        Form.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 190, -1));

        jLabel20.setText("Email Address");
        Form.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 150, -1));
        Form.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 530, 10));

        jLabel12.setText("Religion*");
        Form.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, -1));
        Form.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 110, -1));

        jLabel13.setText("Nationality");
        Form.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 66, -1));
        Form.add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 100, -1));

        lotNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotNumActionPerformed(evt);
            }
        });
        Form.add(lotNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, -1));

        jLabel10.setText("Block Number");
        Form.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));

        jLabel11.setText("Street*");
        Form.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        Form.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alive", "Dead", "Missing", " " }));
        Form.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 60, -1));

        jLabel24.setText("Status");
        Form.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel14.setText("Occupation");
        Form.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, -1));
        Form.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 130, -1));
        Form.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 530, 10));

        jLabel25.setText("First Name*");
        Form.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Basic Information");
        Form.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));
        Form.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 530, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Additional Information");
        Form.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 210, -1));
        Form.add(sss, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 160, -1));

        jLabel15.setText("SSS");
        Form.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel16.setText("PhilHealth");
        Form.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 380, 60, -1));
        Form.add(philHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 400, 160, -1));

        jLabel17.setText("TIN");
        Form.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));
        Form.add(tin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 160, -1));
        Form.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 70, -1));

        jLabel21.setText("Height");
        Form.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel22.setText("Weight");
        Form.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));
        Form.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 70, -1));

        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        Form.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 530, -1));

        jPanel3.add(Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 570, 590));

        SideBar.setBackground(new java.awt.Color(51, 51, 51));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Menu");
        SideBar.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        homePage.setBackground(new java.awt.Color(51, 51, 51));
        homePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database_100.png"))); // NOI18N
        homePage.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        homeLabel.setBackground(new java.awt.Color(204, 204, 204));
        homeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(153, 153, 153));
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });
        homePage.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        SideBar.add(homePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 50));

        databasePage.setBackground(new java.awt.Color(102, 102, 102));
        databasePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database_100.png"))); // NOI18N
        databasePage.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Database");
        databasePage.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        SideBar.add(databasePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 50));

        documentPage.setBackground(new java.awt.Color(51, 51, 51));
        documentPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database_100.png"))); // NOI18N
        documentPage.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        documentLabel.setBackground(new java.awt.Color(204, 204, 204));
        documentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        documentLabel.setForeground(new java.awt.Color(153, 153, 153));
        documentLabel.setText("Documents");
        documentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                documentLabelMouseClicked(evt);
            }
        });
        documentPage.add(documentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        SideBar.add(documentPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 50));

        reportsPage.setBackground(new java.awt.Color(51, 51, 51));
        reportsPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database_100.png"))); // NOI18N
        reportsPage.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        reportLabel.setBackground(new java.awt.Color(204, 204, 204));
        reportLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportLabel.setForeground(new java.awt.Color(153, 153, 153));
        reportLabel.setText("Reports");
        reportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportLabelMouseClicked(evt);
            }
        });
        reportsPage.add(reportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        SideBar.add(reportsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 50));

        officialsPage.setBackground(new java.awt.Color(51, 51, 51));
        officialsPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database_100.png"))); // NOI18N
        officialsPage.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        officialLabel.setBackground(new java.awt.Color(204, 204, 204));
        officialLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        officialLabel.setForeground(new java.awt.Color(153, 153, 153));
        officialLabel.setText("Officials");
        officialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                officialLabelMouseClicked(evt);
            }
        });
        officialsPage.add(officialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        SideBar.add(officialsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 210, 50));

        aboutUs.setBackground(new java.awt.Color(51, 51, 51));
        aboutUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database_100.png"))); // NOI18N
        aboutUs.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        aboutUsLabel.setBackground(new java.awt.Color(204, 204, 204));
        aboutUsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aboutUsLabel.setForeground(new java.awt.Color(153, 153, 153));
        aboutUsLabel.setText("About Us");
        aboutUsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsLabelMouseClicked(evt);
            }
        });
        aboutUs.add(aboutUsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 140, 50));

        SideBar.add(aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 50));

        jPanel3.add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 650));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void suffixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suffixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suffixActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void lotNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotNumActionPerformed

    private void civilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civilStatusActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);

            System.out.println("Connected ka na Oracle database pre");
            String query = "INSERT INTO MOCKDATABASEFORITRAK "
                    + "(FIRSTNAME, MIDDLENAME, LASTNAME, SUFFIX, BIRTHDATE, GENDER, SEX, HOUSENUMBER, STREET, CIVILSTATUS, RELIGION, "
                    + "STATUS, NATIONALITY, OCCUPATION, SSS, PHILHEALTH, TIN, TELEPHONENUMBER, MOBILENUMBER, HEIGHT, WEIGHT, EMAILADDRESS, IMAGE1, IMAGE2) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement stmnt = conn.prepareStatement(query);
            
            stmnt.setString(1, firstName.getText());
            stmnt.setString(2, middleName.getText());
            stmnt.setString(3, lastName.getText());
            stmnt.setString(4, suffix.getText());
            stmnt.setString(5, date.getText());
            stmnt.setString(6, gender.getText());
            stmnt.setString(7, (String) sexBox.getSelectedItem());
            stmnt.setString(8, lotNum.getText());
            stmnt.setString(9, street.getText());
            stmnt.setString(10, (String) civilStatus.getSelectedItem());
            stmnt.setString(11, religion.getText());
            stmnt.setString(12, (String) status.getSelectedItem());
            stmnt.setString(13, nationality.getText());
            stmnt.setString(14, occupation.getText());
            stmnt.setString(15, sss.getText());
            stmnt.setString(16, philHealth.getText());
            stmnt.setString(17, tin.getText());
            stmnt.setString(18, telephone.getText());
            stmnt.setString(19, mobile.getText());
            stmnt.setString(20, height.getText());
            stmnt.setString(21, weight.getText());
            stmnt.setString(22, emailAddress.getText());
            
            InputStream onebyone = new FileInputStream(""+fileName1x1.getText()+"");
            InputStream signature = new FileInputStream(""+fileNameSignature.getText()+"");
           
            if(fileName1x1 == null){
                fileName1x1.setText("C:\\Users\\user\\Documents\\PicturesUsed\\default1x1.jpg");
                stmnt.setBlob(23, onebyone);
            
                }
            
            else{
                stmnt.setBlob(23, onebyone);
                }
            
            if(fileNameSignature == null){
                fileNameSignature.setText("C:\\Users\\user\\Documents\\PicturesUsed\\signatureDefault.png");
                stmnt.setBlob(24, signature);
                }
            
            else{
                stmnt.setBlob(24, signature);
                }
            
            stmnt.execute();
            conn.close();
            System.out.println("Tama ka na pre");

        }
        catch(Exception e){
            System.err.println(e);
        }   
    }//GEN-LAST:event_insertActionPerformed

    private void uploadPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPictureActionPerformed
        // TODO add your handling code here:
      JFileChooser chooser = new JFileChooser();
     chooser.showOpenDialog(null);
     File f = chooser.getSelectedFile();
     String filename = f.getAbsolutePath();
     fileName1x1.setText(filename);
     
     Image getAbsolutePath = null;
     ImageIcon icon = new ImageIcon(filename);
     Image image = icon.getImage().getScaledInstance(157, 110,Image.SCALE_SMOOTH);
     img1x1.setIcon(icon);
        
    }//GEN-LAST:event_uploadPictureActionPerformed

    private void fileName1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileName1x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileName1x1ActionPerformed

    private void uploadSignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadSignatureActionPerformed
        // TODO add your handling code here:
        
     JFileChooser chooser = new JFileChooser();
     chooser.showOpenDialog(null);
     File f = chooser.getSelectedFile();
     String filename = f.getAbsolutePath();
     fileNameSignature.setText(filename);
     
     Image getAbsolutePath = null;
     ImageIcon icon = new ImageIcon(filename);
     Image image = icon.getImage().getScaledInstance(300, 300,Image.SCALE_SMOOTH);
     imageSignature.setIcon(icon);
    }//GEN-LAST:event_uploadSignatureActionPerformed

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        new C_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeLabelMouseClicked

    private void documentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentLabelMouseClicked
        new H_Documents().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_documentLabelMouseClicked

    private void reportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseClicked
        new G_Reports().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportLabelMouseClicked

    private void officialLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officialLabelMouseClicked
        new F_Officials().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_officialLabelMouseClicked

    private void aboutUsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutUsLabelMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        new J_Database().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertForm_Resident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertForm_Resident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertForm_Resident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertForm_Resident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertForm_Resident().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form;
    private javax.swing.JPanel Photo;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel aboutUs;
    private javax.swing.JLabel aboutUsLabel;
    private javax.swing.JLabel backButton;
    private javax.swing.JComboBox<String> civilStatus;
    private javax.swing.JPanel databasePage;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JLabel documentLabel;
    private javax.swing.JPanel documentPage;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField fileName1x1;
    private javax.swing.JTextField fileNameSignature;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel imageSignature;
    private javax.swing.JLabel img1x1;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField lotNum;
    private javax.swing.JTextField middleName;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField occupation;
    private javax.swing.JLabel officialLabel;
    private javax.swing.JPanel officialsPage;
    private javax.swing.JTextField philHealth;
    private javax.swing.JTextField religion;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JPanel reportsPage;
    private javax.swing.JComboBox<String> sexBox;
    private javax.swing.JTextField sss;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField street;
    private javax.swing.JTextField suffix;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField tin;
    private javax.swing.JButton uploadPicture;
    private javax.swing.JButton uploadSignature;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
