
  CREATE TABLE "SYSTEM"."MOCKDATABASEFORITRAK" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"MIDDLENAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SUFFIX" VARCHAR2(20 BYTE), 
	"BIRTHDATE" DATE NOT NULL ENABLE, 
	"GENDER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SEX" CHAR(1 BYTE) NOT NULL ENABLE, 
	"HOUSENUMBER" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CIVILSTATUS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"RELIGION" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"STATUS" CHAR(2 BYTE) NOT NULL ENABLE, 
	"NATIONALITY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"OCCUPATION" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SSS" NUMBER, 
	"PHILHEALTH" NUMBER, 
	"TIN" NUMBER, 
	"TELEPHONENUMBER" NUMBER NOT NULL ENABLE, 
	"MOBILENUMBER" NUMBER, 
	"HEIGHT" FLOAT(126) NOT NULL ENABLE, 
	"WEIGHT" FLOAT(126) NOT NULL ENABLE, 
	"EMAILADDRESS" VARCHAR2(50 BYTE), 
	"IMAGE1" BLOB, 
	"IMAGE2" BLOB, 
	 CONSTRAINT "MOCKDB_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"   NO INMEMORY 
 LOB ("IMAGE1") STORE AS BASICFILE "SYS_LOB0000074012C00024$$"(
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE2") STORE AS BASICFILE "SYS_LOB0000074012C00025$$"(
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

