--------------------------------------------------------
--  File created - Tuesday-October-12-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESIDENTS_DB_DEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RESIDENTS_DB_DEL" 
   (	"ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"MIDDLENAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"SUFFIXNAME" VARCHAR2(20 BYTE), 
	"BIRTHDATE" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(50 BYTE), 
	"SEX" CHAR(1 BYTE), 
	"HOUSENUMBER" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"CIVILSTATUS" VARCHAR2(50 BYTE), 
	"RELIGION" VARCHAR2(50 BYTE), 
	"STATUS" CHAR(7 BYTE), 
	"NATIONALITY" VARCHAR2(50 BYTE), 
	"OCCUPATION" VARCHAR2(50 BYTE), 
	"SSS" NUMBER, 
	"PHILHEALTH" NUMBER, 
	"TIN" NUMBER, 
	"TELEPHONENUMBER" NUMBER, 
	"MOBILENUMBER" NUMBER, 
	"HEIGHT" FLOAT(126), 
	"WEIGHT" FLOAT(126), 
	"EMAILADDRESS" VARCHAR2(50 BYTE), 
	"IMAGE1" BLOB, 
	"IMAGE2" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE1") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE2") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.RESIDENTS_DB_DEL
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table RESIDENTS_DB_DEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("STREET" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("CIVILSTATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("RELIGION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("NATIONALITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("OCCUPATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("TELEPHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESIDENTS_DB_DEL" MODIFY ("WEIGHT" NOT NULL ENABLE);
